import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cors = { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type' };
Deno.serve(async (request) => {
  if (request.method === 'OPTIONS') return new Response('ok', { headers: cors });
  try {
    const authorization = request.headers.get('Authorization'); if (!authorization) return reply({ error: 'Authentication Required' }, 401);
    const client = createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_ANON_KEY')!, { global: { headers: { Authorization: authorization } } });
    const { data: { user } } = await client.auth.getUser(); if (!user) return reply({ error: 'Authentication Required' }, 401);
    const body = await request.json(); const urls = Array.isArray(body.imageDataUrls) ? body.imageDataUrls.slice(0, 4) : [];
    const images = urls.map((url: unknown) => typeof url === 'string' ? url.match(/^data:(image\/[a-zA-Z0-9.+-]+);base64,(.+)$/) : null);
    if (!images.length || images.some((image: unknown) => !image)) return reply({ error: 'Choose Between 1 And 4 Valid Workout Images' }, 400);
    const key = Deno.env.get('GEMINI_API_KEY'); if (!key) return reply({ error: 'Workout Analysis Is Not Configured' }, 503);
    const note = typeof body.note === 'string' ? body.note.slice(0, 500) : '';
    const parts = [{ text: prompt(note, images.length) }, ...images.map((image: RegExpMatchArray | null) => ({ inlineData: { mimeType: image![1], data: image![2] } }))];
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${Deno.env.get('GEMINI_MODEL') ?? 'gemini-3.1-flash-lite'}:generateContent?key=${key}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ contents: [{ parts }], generationConfig: { responseMimeType: 'application/json', temperature: 0 } }) });
    if (!response.ok) return reply({ error: 'Workout Analysis Failed' }, 502);
    const result = await response.json(); const text = result?.candidates?.[0]?.content?.parts?.[0]?.text;
    if (typeof text !== 'string') return reply({ error: 'Workout Analysis Returned No Result' }, 502);
    return reply({ data: normalize(JSON.parse(text), images.length) });
  } catch (error) { console.error('[analyze-workout]', error); return reply({ error: 'Workout Analysis Failed' }, 500); }
});
function reply(body: unknown, status = 200) { return new Response(JSON.stringify(body), { status, headers: { ...cors, 'Content-Type': 'application/json' } }); }
function prompt(note: string, count: number) { return `Precisely transcribe ${count} ordered image tile(s) from ONE workout screenshot set. Inspect every tile from top to bottom before answering. Overlapping tiles may repeat values; keep each metric only once. ${note ? `User note: ${note}` : ''}

For a running workout, prioritize the labeled Workout Details values: workout date, distance, duration, average pace, average heart rate, calories, average cadence and elevation gain. Then inspect later tiles for VO2 max and estimated sweat loss. Convert the displayed date to YYYY-MM-DD. Preserve duration and pace as visible strings. Numeric fields must be JSON numbers without units.

Do not copy lap pace into avgPace. Do not copy heart-rate-zone boundaries into avgHR or maxHR. Do not infer maxHR when only average HR is shown. Do not infer values from maps, charts, colored bars, weather, achievements or axis labels. If duplicate labels conflict, return null for that field, explain both values in unclearFields and set needsReview true.

For swimming, set workoutKind to swimming and swimKind to pool or open_water. Use distanceM rather than converting the primary distance to kilometers. Preserve swim pace with its /100 m unit. Also transcribe poolLengthM, totalLengths, totalStrokes, avgSwolf and bestSwolf when explicitly labeled.

For Circuit training, Weight training, Strength training or Resistance training, set workoutKind to strength and copy the visible activity title into workoutName. Do not require an exercise list when the screenshot only contains session-level metrics. Do not return distance, pace, cadence or elevation for strength sessions unless explicitly applicable.

Return JSON only: {extracted:{workoutKind,workoutName,date,distanceKm,distanceM,duration,avgPace,maxPace,avgSpeedKmh,maxSpeedKmh,avgHR,maxHR,cadence,maxCadence,steps,calories,elevationGain,vo2Max,sweatLossMl,swimKind,poolLengthM,totalLengths,totalStrokes,avgSwolf,bestSwolf,visibleMetrics,intensity,exercises},coach:{workoutSummary,intensityAssessment,trainingLoadNote,wasTooHard,recoveryAdvice,nutritionAfterWorkout,nextWorkoutSuggestion,coachNote},confidence,unclearFields,needsReview}. workoutKind must be outdoor_run, treadmill, strength, walk, cycling, swimming, or other. Use null for unavailable metrics. Write all coach text and unclearFields in Thai. Keep keys and enum values in English.`; }
function normalize(value: unknown, imageCount: number) { const data = obj(value), extracted = obj(data.extracted), coach = obj(data.coach); const num = (v: unknown) => { if (typeof v === 'number' && Number.isFinite(v)) return v; if (typeof v === 'string') { const parsed = Number(v.replace(/,/g, '').match(/-?\d+(?:\.\d+)?/)?.[0]); return Number.isFinite(parsed) ? parsed : null; } return null; }; const str = (v: unknown) => typeof v === 'string' && v.trim() ? v.trim() : null; const kinds = ['outdoor_run','treadmill','strength','walk','cycling','swimming','other']; const swimKinds = ['pool','open_water']; return { extracted: { workoutKind: kinds.includes(String(extracted.workoutKind)) ? extracted.workoutKind : 'other', workoutName:str(extracted.workoutName), date: str(extracted.date), distanceKm:num(extracted.distanceKm), distanceM:num(extracted.distanceM), duration:str(extracted.duration), avgPace:str(extracted.avgPace), maxPace:str(extracted.maxPace), avgSpeedKmh:num(extracted.avgSpeedKmh), maxSpeedKmh:num(extracted.maxSpeedKmh), avgHR:num(extracted.avgHR), maxHR:num(extracted.maxHR), cadence:num(extracted.cadence), maxCadence:num(extracted.maxCadence), steps:num(extracted.steps), calories:num(extracted.calories), elevationGain:num(extracted.elevationGain), vo2Max:num(extracted.vo2Max), sweatLossMl:num(extracted.sweatLossMl), swimKind:swimKinds.includes(String(extracted.swimKind))?extracted.swimKind:null, poolLengthM:num(extracted.poolLengthM), totalLengths:num(extracted.totalLengths), totalStrokes:num(extracted.totalStrokes), avgSwolf:num(extracted.avgSwolf), bestSwolf:num(extracted.bestSwolf), visibleMetrics:Array.isArray(extracted.visibleMetrics)?extracted.visibleMetrics:[], mergedFromMultipleImages:imageCount>1, exercises:Array.isArray(extracted.exercises)?extracted.exercises:null, muscleGroups:Array.isArray(extracted.muscleGroups)?extracted.muscleGroups:null, intensity:['easy','moderate','hard'].includes(String(extracted.intensity))?extracted.intensity:null, rpe:num(extracted.rpe) }, coach: { workoutSummary:str(coach.workoutSummary)??'', intensityAssessment:str(coach.intensityAssessment)??'', trainingLoadNote:str(coach.trainingLoadNote)??'', wasTooHard:coach.wasTooHard===true, recoveryAdvice:str(coach.recoveryAdvice)??'', nutritionAfterWorkout:str(coach.nutritionAfterWorkout)??'', nextWorkoutSuggestion:str(coach.nextWorkoutSuggestion)??'', coachNote:str(coach.coachNote)??'' }, confidence:['low','medium','high'].includes(String(data.confidence))?data.confidence:'low', unclearFields:Array.isArray(data.unclearFields)?data.unclearFields:[], needsReview:data.needsReview!==false }; }
function obj(value: unknown): Record<string, unknown> { return value && typeof value === 'object' ? value as Record<string, unknown> : {}; }
