import { useEffect, useRef, useState } from 'react';
import { useHistory } from 'react-router-dom';
import { IonIcon, IonSpinner } from '@ionic/react';
import { cameraOutline, checkmarkCircleOutline, closeOutline, fitnessOutline } from 'ionicons/icons';
import { analyzeWorkoutImages } from '@/lib/workoutUpload';
import { createHistoryItem, saveHistoryItems } from '@/lib/cloudHistory';
import { dateKeyToRecordedAt, todayBangkokDateKey } from '@/lib/date';
import type { WorkoutAnalysis } from '@/types/logs';
import UploadDateField from '@/components/UploadDateField';
import { buildReviewReconciliationInput } from '@/lib/reconciliationPolicy';

const workoutKinds: WorkoutAnalysis['extracted']['workoutKind'][] = ['outdoor_run', 'treadmill', 'walk', 'cycling', 'swimming', 'strength', 'other'];
export default function WorkoutUploadFlow() {
  const history = useHistory(); const [images, setImages] = useState<Array<{ file: File; url: string }>>([]); const imagesRef = useRef(images); imagesRef.current = images;
  const [note,setNote]=useState(''); const [workout,setWorkout]=useState<WorkoutAnalysis|null>(null); const [reviewBaseline,setReviewBaseline]=useState<WorkoutAnalysis['extracted']|null>(null); const [date,setDate]=useState(todayBangkokDateKey()); const [loading,setLoading]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
  useEffect(()=>()=>imagesRef.current.forEach((image)=>URL.revokeObjectURL(image.url)),[]);
  const choose=(files:File[])=>{const room=4-images.length;setImages((current)=>[...current,...files.slice(0,room).map((file)=>({file,url:URL.createObjectURL(file)}))]);setError(files.length>room?'You Can Add Up To 4 Screenshots.':'');};
  const remove=(index:number)=>setImages((current)=>{const target=current[index];if(target)URL.revokeObjectURL(target.url);return current.filter((_,i)=>i!==index);});
  const analyze=async()=>{setLoading(true);setError('');try{const result=await analyzeWorkoutImages(images.map((image)=>image.file),note);setWorkout(result);setReviewBaseline({...result.extracted});if(result.extracted.date&&/^\d{4}-\d{2}-\d{2}$/.test(result.extracted.date))setDate(result.extracted.date);}catch(cause){setError(cause instanceof Error?cause.message:'Workout Analysis Failed');}finally{setLoading(false);}};
  const update=(values:Partial<WorkoutAnalysis['extracted']>)=>workout&&setWorkout({...workout,extracted:{...workout.extracted,...values}});
  const reset=()=>{images.forEach((image)=>URL.revokeObjectURL(image.url));setImages([]);setNote('');setWorkout(null);setReviewBaseline(null);setDate(todayBangkokDateKey());setSaving(false);setError('');};
  const save=async()=>{if(!workout)return;setSaving(true);setError('');const reviewedExtracted={...workout.extracted,date};const reconciliationInput=buildReviewReconciliationInput(reviewBaseline??{},reviewedExtracted,workoutReviewFieldKeys);const item=createHistoryItem('workout',{...workout,extracted:reviewedExtracted,reconciliationInput});item.dateKey=date;item.recordedAt=dateKeyToRecordedAt(date);item.source={provider:'generic_image',importType:'image',importedAt:new Date().toISOString()};const result=await saveHistoryItems([item]);if(result.ok){reset();history.push(`/activity/workout/${encodeURIComponent(item.id)}`);}else{setError(result.error??'Could Not Save This Workout');setSaving(false);}};
  const reviewFields=workout?.extracted.workoutKind==='swimming'?swimMetricFields:workout?.extracted.workoutKind==='strength'?strengthMetricFields:metricFields;
if(workout)return <section className="upload-review workout-review"><header><p>Review Workout</p><h1>Check Your Workout</h1><span>Only save metrics that are visible and correct.</span></header><section className="workout-review-card"><header><p>Workout</p><h2>Session Details</h2></header><label><span>Workout Type</span><select value={workout.extracted.workoutKind} onChange={(event)=>update({workoutKind:event.target.value as WorkoutAnalysis['extracted']['workoutKind']})}>{workoutKinds.map((kind)=><option value={kind} key={kind}>{label(kind)}</option>)}</select></label><UploadDateField label="Workout Date" value={date} max={todayBangkokDateKey()} onChange={setDate}/></section><section className="upload-review-metrics-section"><header><p>Metrics</p><h2>Workout Metrics</h2></header><div className="upload-review-metrics">{reviewFields.map((field)=><label key={field.key}><span>{field.label}</span><input type={field.numeric?'number':'text'} min={field.numeric?'0':undefined} inputMode={field.numeric?'decimal':undefined} value={String(workout.extracted[field.key]??'')} onChange={(event)=>update({[field.key]:field.numeric?(event.target.value===''?null:Number(event.target.value)):event.target.value||null})}/></label>)}</div></section>{error&&<p className="upload-error">{error}</p>}<div className="upload-actions"><button type="button" onClick={()=>setWorkout(null)}>Back To Photos</button><button type="button" disabled={saving} onClick={()=>void save()}>{saving?<IonSpinner name="crescent"/>:<IonIcon icon={checkmarkCircleOutline}/>}Save Workout</button></div></section>;
  return <><header className="upload-intro"><p>Add Workout</p><h1>Log Your Workout</h1><span>Add up to four screenshots from the same workout.</span></header><section className="upload-section"><div className="upload-section-title"><IonIcon icon={fitnessOutline}/><div><p>Workout Screenshots</p><h2>Add Screenshots</h2><span>{images.length}/4 selected</span></div></div>{images.length>0&&<div className="upload-preview-grid">{images.map((image,index)=><div key={image.url}><img src={image.url} alt={`Workout Screenshot ${index+1}`}/><button type="button" onClick={()=>remove(index)} aria-label={`Remove Workout Screenshot ${index+1}`}><IonIcon icon={closeOutline}/></button></div>)}</div>}<label className="upload-picker"><IonIcon icon={cameraOutline}/><strong>{images.length?'Add More Screenshots':'Choose Workout Screenshots'}</strong><span>Summary, heart rate, splits, or workout details</span><input type="file" multiple accept="image/*" onChange={(event)=>{choose(Array.from(event.target.files??[]));event.target.value='';}}/></label><label className="upload-note"><span>Add Details <em>Optional</em></span><textarea value={note} onChange={(event)=>setNote(event.target.value)} maxLength={500} placeholder="Example: Easy outdoor run"/></label></section>{error&&<p className="upload-error">{error}</p>}<button type="button" className="upload-primary" disabled={!images.length||loading} onClick={()=>void analyze()}>{loading?<><IonSpinner name="crescent"/>Reviewing Screenshots...</>:`Review Workout${images.length>1?` From ${images.length} Screenshots`:''}`}</button></>;
}
const metricFields=[{key:'distanceKm',label:'Distance (km)',numeric:true},{key:'duration',label:'Duration',numeric:false},{key:'avgPace',label:'Average Pace',numeric:false},{key:'maxPace',label:'Max Pace',numeric:false},{key:'avgSpeedKmh',label:'Average Speed (km/h)',numeric:true},{key:'maxSpeedKmh',label:'Max Speed (km/h)',numeric:true},{key:'avgHR',label:'Average HR',numeric:true},{key:'maxHR',label:'Max HR',numeric:true},{key:'calories',label:'Calories',numeric:true},{key:'steps',label:'Steps',numeric:true},{key:'cadence',label:'Average Cadence (spm)',numeric:true},{key:'maxCadence',label:'Max Cadence (spm)',numeric:true},{key:'elevationGain',label:'Elevation Gain (m)',numeric:true},{key:'vo2Max',label:'VO2 Max',numeric:true},{key:'sweatLossMl',label:'Sweat Loss (ml)',numeric:true}] as const;
const swimMetricFields=[{key:'distanceM',label:'Distance (m)',numeric:true},{key:'duration',label:'Duration',numeric:false},{key:'avgPace',label:'Average Pace (/100 m)',numeric:false},{key:'avgSpeedKmh',label:'Average Speed (km/h)',numeric:true},{key:'avgHR',label:'Average HR',numeric:true},{key:'maxHR',label:'Max HR',numeric:true},{key:'calories',label:'Calories',numeric:true},{key:'poolLengthM',label:'Pool Length (m)',numeric:true},{key:'totalLengths',label:'Total Lengths',numeric:true},{key:'totalStrokes',label:'Total Strokes',numeric:true},{key:'avgSwolf',label:'Average SWOLF',numeric:true},{key:'bestSwolf',label:'Best SWOLF',numeric:true}] as const;
const strengthMetricFields=[{key:'workoutName',label:'Workout Name',numeric:false},{key:'duration',label:'Duration',numeric:false},{key:'avgHR',label:'Average HR',numeric:true},{key:'maxHR',label:'Max HR',numeric:true},{key:'calories',label:'Calories',numeric:true}] as const;
const workoutReviewFieldKeys=['date','workoutKind',...new Set([...metricFields,...swimMetricFields,...strengthMetricFields].map((field)=>field.key))] as const;
function label(value:string){return value.replace(/_/g,' ').replace(/\b\w/g,(letter)=>letter.toUpperCase());}
