import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};
Deno.serve(async(request)=>{if(request.method==='OPTIONS')return new Response('ok',{headers:cors});try{const auth=request.headers.get('Authorization');if(!auth)return reply({error:'Authentication Required'},401);const client=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:auth}}});const{data:{user}}=await client.auth.getUser();if(!user)return reply({error:'Authentication Required'},401);const body=await request.json();const urls=Array.isArray(body.imageDataUrls)?body.imageDataUrls.slice(0,4):[];const images=urls.map((url:unknown)=>typeof url==='string'?url.match(/^data:(image\/[a-zA-Z0-9.+-]+);base64,(.+)$/):null);if(!images.length||images.some((image:unknown)=>!image))return reply({error:'Choose Between 1 And 4 Valid Sleep Images'},400);const key=Deno.env.get('GEMINI_API_KEY');if(!key)return reply({error:'Sleep Analysis Is Not Configured'},503);const note=typeof body.note==='string'?body.note.slice(0,500):'';const parts=[{text:prompt(note,images.length)},...images.map((image:RegExpMatchArray|null)=>({inlineData:{mimeType:image![1],data:image![2]}}))];const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${Deno.env.get('GEMINI_MODEL')??'gemini-3.1-flash-lite'}:generateContent?key=${key}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts}],generationConfig:{responseMimeType:'application/json',temperature:0}})});if(!response.ok)return reply({error:'Sleep Analysis Failed'},502);const result=await response.json();const text=result?.candidates?.[0]?.content?.parts?.[0]?.text;if(typeof text!=='string')return reply({error:'Sleep Analysis Returned No Result'},502);const normalized=normalize(JSON.parse(text),images.length);if(!hasSleepSignals(normalized))return reply({error:'No Readable Sleep Metrics Found'},422);return reply({data:normalized});}catch(error){console.error('[analyze-sleep]',error);return reply({error:'Sleep Analysis Failed'},500);}});
function reply(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json'}})}
function prompt(note:string,count:number){return `You are performing a precise transcription of ${count} high-resolution sleep screenshot(s) from ONE night. Inspect every image from top to bottom before producing output. ${note?`User note: ${note}`:''}

READING PROCEDURE
1. Read the Sleep summary: displayed date, Sleep Score, Time In Bed, Actual Sleep Time, bedtime and wake time.
2. Read Sleep stages: Awake, REM, Light and Deep. Prefer displayed duration values over calculating from percentages.
3. Read overnight signals: Sleeping Heart Rate average, Sleeping HRV average, Respiratory Rate average, Blood Oxygen average/lowest and Skin Temperature change from baseline.
4. Read Energy summary separately. Energy Score is NOT Sleep Score.
5. Re-scan all screenshots for values missed in earlier sections. The same metric may appear in more than one image.
6. Cross-check duplicates. If identical, keep one. If conflicting, use null, list the field and both visible values in unclearFields, and set needsReview true.

LABEL MAPPING
- "Sleep time" beside the bedtime range means Time In Bed.
- "Actual sleep time" means actualSleepDurationMinutes.
- "Heart rate during sleep" or "Sleeping HR" means avgSleepingHeartRate and restingHR.
- "Heart rate variability during sleep" or "Sleeping HRV" means avgSleepingHrv and hrv.
- "Respiratory rate during sleep" means avgRespiratoryRate.
- Do not copy a chart-axis maximum, minimum, legend, percentage, 7-day value or baseline into an average field.

Return JSON only: {"extracted":{...},"confidence":"low|medium|high","unclearFields":[],"needsReview":true|false}.
Numeric fields MUST be JSON numbers without units: actualSleepDurationMinutes, timeInBedMinutes, avgSleepingHeartRate, avgSleepingHrv, avgRespiratoryRate, sleepStageAwakeMinutes, sleepStageRemMinutes, sleepStageLightMinutes, sleepStageDeepMinutes, sleepLatencyMinutes, avgSpO2Percent, lowestSpO2Percent, skinTemperatureDeltaC, sleepScore, energyScore, restingHR, hrv.
String fields: date (YYYY-MM-DD), sleepDuration (example: 7h 20m), sleepStartTime, sleepEndTime, sleepQualityLabel, visibleNotes.
Convert displayed hours/minutes to total minutes for numeric minute fields. Preserve negative temperature change. Use null unless the exact value and its label are clearly visible. Never infer values from graph shapes. Never calculate Recovery or Readiness. Write visibleNotes and unclearFields in Thai; keep keys English.`}
function normalize(value:unknown,imageCount:number){const data=obj(value),e=obj(data.extracted??data),nested=obj(e.sleepStageMinutes);const n=(v:unknown)=>{if(typeof v==='number'&&Number.isFinite(v))return v;if(typeof v==='string'){const parsed=Number(v.replace(/,/g,'').match(/-?\d+(?:\.\d+)?/)?.[0]);return Number.isFinite(parsed)?parsed:null}return null};const s=(v:unknown)=>typeof v==='string'&&v.trim()?v.trim():null;const durationText=s(e.sleepDuration??e.actualSleepDurationText);const durationMinutes=n(e.actualSleepDurationMinutes??e.actualSleepTimeMinutes??e.totalSleepTimeMinutes??e.sleepDurationMinutes)??parseDuration(durationText);const stages={awake:n(e.sleepStageAwakeMinutes??e.awakeMinutes??nested.awake),rem:n(e.sleepStageRemMinutes??e.remSleepMinutes??nested.rem),light:n(e.sleepStageLightMinutes??e.lightSleepMinutes??nested.light),deep:n(e.sleepStageDeepMinutes??e.deepSleepMinutes??nested.deep)};const explicitTimeInBed=n(e.timeInBedMinutes??e.inBedMinutes);const derivedTimeInBed=explicitTimeInBed==null&&durationMinutes!=null&&stages.awake!=null?durationMinutes+stages.awake:null;const sleepingHrv=n(e.avgSleepingHrv??e.sleepingHrv??e.heartRateVariabilityDuringSleep??e.hrv);const sleepingHr=n(e.avgSleepingHeartRate??e.sleepingHeartRateAverage??e.heartRateDuringSleep??e.sleepingHR??e.restingHR);const respiratoryRate=n(e.avgRespiratoryRate??e.respiratoryRateDuringSleep??e.respiratoryRate);return{extracted:{date:s(e.date),sleepDuration:durationText??minutesText(durationMinutes),actualSleepDurationMinutes:durationMinutes,timeInBedMinutes:explicitTimeInBed??derivedTimeInBed,timeInBedDerived:explicitTimeInBed==null&&derivedTimeInBed!=null,sleepStartTime:s(e.sleepStartTime),sleepEndTime:s(e.sleepEndTime),avgSleepingHeartRate:sleepingHr,avgSleepingHrv:sleepingHrv,avgRespiratoryRate:respiratoryRate,sleepStageAwakeMinutes:stages.awake,sleepStageRemMinutes:stages.rem,sleepStageLightMinutes:stages.light,sleepStageDeepMinutes:stages.deep,sleepStageMinutes:stages,sleepLatencyMinutes:n(e.sleepLatencyMinutes??e.sleepLatency),avgSpO2Percent:n(e.avgSpO2Percent??e.averageBloodOxygen??e.avgBloodOxygen),lowestSpO2Percent:n(e.lowestSpO2Percent??e.lowestBloodOxygen),skinTemperatureDeltaC:n(e.skinTemperatureDeltaC??e.skinTemperatureChange),sleepDurationSource:durationMinutes!=null?'actual':'unknown',mergedFromMultipleImages:imageCount>1,sleepScore:n(e.sleepScore),energyScore:n(e.energyScore),restingHR:n(e.restingHR??sleepingHr),hrv:n(e.hrv??sleepingHrv),sleepQualityLabel:s(e.sleepQualityLabel),visibleNotes:s(e.visibleNotes)},coach:{readinessScore:null,readinessLabel:'unavailable',aiSummary:'',todayRecommendation:'',nutritionFocus:'',recoveryFocus:'',sleepFocus:'',warningNotes:''},confidence:['low','medium','high'].includes(String(data.confidence))?data.confidence:'low',unclearFields:Array.isArray(data.unclearFields)?data.unclearFields:[],needsReview:data.needsReview!==false};}
function minutesText(value:number|null){if(value==null)return null;return `${Math.floor(value/60)}h ${Math.round(value%60)}m`}
function parseDuration(value:string|null){if(!value)return null;const hours=Number(value.match(/(\d+(?:\.\d+)?)\s*(?:h|hr|hour|\u0e0a\u0e21)/i)?.[1]??0);const minutes=Number(value.match(/(\d+)\s*(?:m|min|minute|\u0e19\u0e32\u0e17\u0e35)/i)?.[1]??0);const total=Math.round(hours*60+minutes);return total>0?total:null}
function hasSleepSignals(value:Record<string,unknown>){const extracted=obj(value.extracted);return ['sleepDuration','actualSleepDurationMinutes','timeInBedMinutes','sleepScore','hrv','restingHR','avgRespiratoryRate','sleepStageAwakeMinutes','sleepStageRemMinutes','sleepStageLightMinutes','sleepStageDeepMinutes'].some((key)=>extracted[key]!=null)}
function obj(value:unknown):Record<string,unknown>{return value&&typeof value==='object'?value as Record<string,unknown>: {}}
